"""
store, item, order

Revision ID: dbb8a7a12f5b
Revises: 6b2aaf557658
Create Date: 2024-11-13 02:12:17.375163
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb8a7a12f5b'
down_revision: Union[str, None] = '6b2aaf557658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('CANCELED', 'ORDERED', 'COMPLETE', name='orderstatus'), nullable=False),
    sa.Column('orderer_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['orderer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_name'), 'store', ['name'], unique=True)
    op.create_table('item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=True)
    op.create_table('order_item_list',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item_list')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_store_name'), table_name='store')
    op.drop_table('store')
    op.drop_table('order')
    # ### end Alembic commands ###
