"""


Revision ID: 7d5ba57fd8b0
Revises: dbb8a7a12f5b
Create Date: 2024-11-17 01:38:04.618580
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5ba57fd8b0'
down_revision: Union[str, None] = 'dbb8a7a12f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item_list', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item_list', 'quantity')
    # ### end Alembic commands ###
