"""
create blocked_token

Revision ID: 86b9a55d847d
Revises: 7d5ba57fd8b0
Create Date: 2024-12-06 04:50:56.820511
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b9a55d847d'
down_revision: Union[str, None] = '7d5ba57fd8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_token',
    sa.Column('token_id', sa.String(length=255), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.execute("""
        CREATE EVENT IF NOT EXISTS delete_expired_blocked_token
        ON SCHEDULE EVERY 1 DAY
            STARTS CURRENT_TIMESTAMP
        DO
            DELETE FROM blocked_token WHERE expired_at < NOW();
               """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EVENT IF EXISTS delete_expired_blocked_token")
    op.drop_table('blocked_token')
    # ### end Alembic commands ###
